# Generated by Django 3.1.5 on 2021-01-27 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='onetoone.place')),
                ('res_name', models.CharField(max_length=50)),
                ('Kacchi', models.BooleanField(default=False)),
                ('Kala_Vuna', models.BooleanField(default=True)),
                ('Beef_Khechuri', models.BooleanField(default=True)),
            ],
        ),
    ]
